<?xml version="1.0" encoding="utf-8"?><Database Name="KiemKeTaiSan" Class="AIDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-GVFBISL\TOMORROW;Initial Catalog=QuanLyThietBi;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="KiemKeTaiSanConnectionString" Provider="Microsoft.Data.SqlClient" />
  <Table Name="dbo.BanKiemKe" Member="BanKiemKes">
    <Type Name="BanKiemKe">
      <Column Name="MaBanKiemKe" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaPhieu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaDV" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoVaTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiSan" Member="TaiSans">
    <Type Name="TaiSan">
      <Column Name="MaTS" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNhomTS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenTS" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="GiaTri" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuongChinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HangSanXuat" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="NamSanXuat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NuocSanXuat" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietPhieuKiemKe" Member="ChiTietPhieuKiemKes">
    <Type Name="ChiTietPhieuKiemKe">
      <Column Name="MaCTPKK" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaPhieu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenTS" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="TenNhomTS" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="GiaTri" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuongThucTe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConTot" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KemPC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MatPC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HangSanXuat" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="NamSanXuat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NuocSanXuat" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaTS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DonVi" Member="DonVis">
    <Type Name="DonVi">
      <Column Name="MaDV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDV" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhuVucPhong" Member="KhuVucPhongs">
    <Type Name="KhuVucPhong">
      <Column Name="MaKV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiPhong" Member="LoaiPhongs">
    <Type Name="LoaiPhong">
      <Column Name="MaLP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiTaiSan" Member="LoaiTaiSans">
    <Type Name="LoaiTaiSan">
      <Column Name="MaLoaiTS" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiTS" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NguoiDung" Member="NguoiDungs">
    <Type Name="NguoiDung">
      <Column Name="MaND" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDV" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HoVaTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ChucDanh" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PhanQuyen" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.NhatKyHoatDong" Member="NhatKyHoatDongs">
    <Type Name="NhatKyHoatDong">
      <Column Name="MaNKHD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HoatDong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ChiTietHoatDong" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NgayHoatDong" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhomTaiSan" Member="NhomTaiSans">
    <Type Name="NhomTaiSan">
      <Column Name="MaNhomTS" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaLoaiTS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenNhomTS" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhanBo" Member="PhanBos">
    <Type Name="PhanBo">
      <Column Name="MaPB" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaTS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaPhong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DvTinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SoLuongHong" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuKiemKe" Member="PhieuKiemKes">
    <Type Name="PhieuKiemKe">
      <Column Name="MaPhieu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaPhong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Phong" Member="Phongs">
    <Type Name="Phong">
      <Column Name="MaPhong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaLP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaKV" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenPhong" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
	<Table Name="dbo.ThanhLy" Member="ThanhLys">
		<Type Name="ThanhLy">
			<Column Name="MaTL" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="MaPB" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
			<Column Name="SoLuongThanhLy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
			<Column Name="GhiChu" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
			<Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
			<Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
		</Type>
	</Table>
</Database>